export const INDIAN_CCTV_CAMERAS = [
  {
    "id": "cctv-del-01",
    "city": "Delhi NCR",
    "name": "India Gate & Kartavya Path Central Axis",
    "lat": 28.6129,
    "lon": 77.2295,
    "elevationM": 28,
    "headingDeg": 280,
    "fovDeg": 72,
    "rangeM": 750,
    "status": "ONLINE",
    "type": "Traffic & Security Surveillance",
    "streamUrl": "https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80",
    "description": "Wide angle optical surveillance facing west along Kartavya Path towards Central Vista."
  },
  {
    "id": "cctv-del-02",
    "city": "Delhi NCR",
    "name": "Connaught Place Inner Circle",
    "lat": 28.6328,
    "lon": 77.2197,
    "elevationM": 32,
    "headingDeg": 125,
    "fovDeg": 68,
    "rangeM": 620,
    "status": "ONLINE",
    "type": "Commercial Hub Transit",
    "streamUrl": "https://images.unsplash.com/photo-1597044141240-ef3b3a4a15a0?auto=format&fit=crop&w=800&q=80",
    "description": "High-density vehicle and pedestrian flow monitoring on Inner Radial 3."
  },
  {
    "id": "cctv-del-03",
    "city": "Delhi NCR",
    "name": "DND Flyway Yamuna Bridge",
    "lat": 28.5833,
    "lon": 77.2882,
    "elevationM": 22,
    "headingDeg": 85,
    "fovDeg": 75,
    "rangeM": 900,
    "status": "ONLINE",
    "type": "Expressway Traffic Optical",
    "streamUrl": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    "description": "Eastbound Yamuna River multi-lane expressway flow camera."
  },
  {
    "id": "cctv-del-04",
    "city": "Delhi NCR",
    "name": "Indira Gandhi International Airport (T3 Airside)",
    "lat": 28.5562,
    "lon": 77.1,
    "elevationM": 35,
    "headingDeg": 260,
    "fovDeg": 80,
    "rangeM": 1200,
    "status": "ONLINE",
    "type": "Aviation Perimeter Sensor",
    "streamUrl": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80",
    "description": "Runway 28/10 touchdown perimeter and apron gate surveillance."
  },
  {
    "id": "cctv-del-05",
    "city": "Delhi NCR",
    "name": "Dhaula Kuan Strategic Interchange",
    "lat": 28.5921,
    "lon": 77.161,
    "elevationM": 24,
    "headingDeg": 45,
    "fovDeg": 70,
    "rangeM": 650,
    "status": "ONLINE",
    "type": "Ring Road Transit Corridor",
    "streamUrl": "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80",
    "description": "Arterial intersection between Cantonment and Central Delhi."
  },
  {
    "id": "cctv-del-06",
    "city": "Delhi NCR",
    "name": "Noida Sector 18 Commercial Hub",
    "lat": 28.5708,
    "lon": 77.3261,
    "elevationM": 20,
    "headingDeg": 310,
    "fovDeg": 65,
    "rangeM": 550,
    "status": "ONLINE",
    "type": "Urban Commerce Transit",
    "streamUrl": "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
    "description": "Atta Market arterial approach and metro station interchange."
  },
  {
    "id": "cctv-bom-01",
    "city": "Mumbai",
    "name": "Bandra-Worli Sea Link Cable-Stayed Span",
    "lat": 19.033,
    "lon": 72.8166,
    "elevationM": 45,
    "headingDeg": 190,
    "fovDeg": 80,
    "rangeM": 1400,
    "status": "ONLINE",
    "type": "Maritime & Coastal Expressway",
    "streamUrl": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "description": "Arabian Sea coastal tollway bridge watching south towards Worli."
  },
  {
    "id": "cctv-bom-02",
    "city": "Mumbai",
    "name": "Chhatrapati Shivaji Maharaj Terminus (CSMT)",
    "lat": 18.94,
    "lon": 72.8353,
    "elevationM": 20,
    "headingDeg": 340,
    "fovDeg": 70,
    "rangeM": 500,
    "status": "ONLINE",
    "type": "Rail Transit Security",
    "streamUrl": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    "description": "Central Railway headquarters plaza and Dr. DN Road vehicular corridor."
  },
  {
    "id": "cctv-bom-03",
    "city": "Mumbai",
    "name": "Marine Drive Queen's Necklace Coastal Arc",
    "lat": 18.9438,
    "lon": 72.8231,
    "elevationM": 18,
    "headingDeg": 160,
    "fovDeg": 85,
    "rangeM": 1100,
    "status": "ONLINE",
    "type": "Coastal Boulevard Optical",
    "streamUrl": "https://images.unsplash.com/photo-1566552881560-0be86c53957f?auto=format&fit=crop&w=800&q=80",
    "description": "Back Bay seafront promenade looking towards Nariman Point."
  },
  {
    "id": "cctv-bom-04",
    "city": "Mumbai",
    "name": "Jawaharlal Nehru Port Trust (JNPT Harbor)",
    "lat": 18.95,
    "lon": 72.95,
    "elevationM": 30,
    "headingDeg": 270,
    "fovDeg": 80,
    "rangeM": 1500,
    "status": "ONLINE",
    "type": "Deepwater Container Port",
    "streamUrl": "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80",
    "description": "Nhava Sheva container berths and channel navigation approaches."
  },
  {
    "id": "cctv-bom-05",
    "city": "Mumbai",
    "name": "Western Express Highway (Andheri Flyover)",
    "lat": 19.1197,
    "lon": 72.8468,
    "elevationM": 26,
    "headingDeg": 15,
    "fovDeg": 72,
    "rangeM": 700,
    "status": "ONLINE",
    "type": "Highway Transit Flow",
    "streamUrl": "https://images.unsplash.com/photo-1544620347-c4fd4a3d5957?auto=format&fit=crop&w=800&q=80",
    "description": "Northbound WEH trunk flow adjacent to Chhatrapati Shivaji Maharaj International Airport."
  },
  {
    "id": "cctv-blr-01",
    "city": "Bengaluru",
    "name": "Silk Board Central Traffic Flyover",
    "lat": 12.9176,
    "lon": 77.6238,
    "elevationM": 25,
    "headingDeg": 350,
    "fovDeg": 75,
    "rangeM": 680,
    "status": "ONLINE",
    "type": "Urban Bottleneck Corridor",
    "streamUrl": "https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80",
    "description": "Hosur Road and Outer Ring Road major electronics transit corridor."
  },
  {
    "id": "cctv-blr-02",
    "city": "Bengaluru",
    "name": "MG Road & Brigade Road Junction",
    "lat": 12.9754,
    "lon": 77.6066,
    "elevationM": 22,
    "headingDeg": 220,
    "fovDeg": 68,
    "rangeM": 520,
    "status": "ONLINE",
    "type": "Central Business District",
    "streamUrl": "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
    "description": "Metro line viaduct and commercial shopping intersection."
  },
  {
    "id": "cctv-blr-03",
    "city": "Bengaluru",
    "name": "Electronic City Elevated Expressway",
    "lat": 12.8452,
    "lon": 77.6602,
    "elevationM": 32,
    "headingDeg": 140,
    "fovDeg": 75,
    "rangeM": 900,
    "status": "ONLINE",
    "type": "Tech Corridor Tollway",
    "streamUrl": "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80",
    "description": "Elevated 4-lane highway linking south Bangalore tech parks."
  },
  {
    "id": "cctv-blr-04",
    "city": "Bengaluru",
    "name": "Kempegowda International Airport Access",
    "lat": 13.1986,
    "lon": 77.7066,
    "elevationM": 28,
    "headingDeg": 310,
    "fovDeg": 78,
    "rangeM": 1000,
    "status": "ONLINE",
    "type": "Airport Trumpet Interchange",
    "streamUrl": "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?auto=format&fit=crop&w=800&q=80",
    "description": "NH 44 trumpet interchange leading to Bengaluru Airport Terminal 1 & 2."
  },
  {
    "id": "cctv-hyd-01",
    "city": "Hyderabad",
    "name": "Cyber Towers Roundabout (HITEC City)",
    "lat": 17.4504,
    "lon": 78.3808,
    "elevationM": 30,
    "headingDeg": 200,
    "fovDeg": 74,
    "rangeM": 700,
    "status": "ONLINE",
    "type": "IT Corridor Arterial",
    "streamUrl": "https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80",
    "description": "Cyberabad central roundabout surveillance camera."
  },
  {
    "id": "cctv-hyd-02",
    "city": "Hyderabad",
    "name": "Hussain Sagar Tank Bund Promenade",
    "lat": 17.4239,
    "lon": 78.4738,
    "elevationM": 18,
    "headingDeg": 90,
    "fovDeg": 76,
    "rangeM": 800,
    "status": "ONLINE",
    "type": "Urban Lake Shoreline",
    "streamUrl": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    "description": "Twin-city connecting causeway between Hyderabad and Secunderabad."
  },
  {
    "id": "cctv-hyd-03",
    "city": "Hyderabad",
    "name": "Outer Ring Road (Gachibowli Junction)",
    "lat": 17.4401,
    "lon": 78.3489,
    "elevationM": 24,
    "headingDeg": 270,
    "fovDeg": 75,
    "rangeM": 950,
    "status": "ONLINE",
    "type": "Orbital Expressway",
    "streamUrl": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    "description": "Hyderabad 8-lane expressway junction near Financial District."
  },
  {
    "id": "cctv-ccu-01",
    "city": "Kolkata",
    "name": "Howrah Bridge Cantilever Span",
    "lat": 22.5851,
    "lon": 88.3468,
    "elevationM": 40,
    "headingDeg": 285,
    "fovDeg": 76,
    "rangeM": 950,
    "status": "ONLINE",
    "type": "Hooghly River & Bridge Transport",
    "streamUrl": "https://images.unsplash.com/photo-1558431382-27e303142255?auto=format&fit=crop&w=800&q=80",
    "description": "Hooghly river navigation channel and vehicular cantilever bridge."
  },
  {
    "id": "cctv-ccu-02",
    "city": "Kolkata",
    "name": "Park Street & Chowringhee Junction",
    "lat": 22.5516,
    "lon": 88.3524,
    "elevationM": 18,
    "headingDeg": 180,
    "fovDeg": 68,
    "rangeM": 520,
    "status": "ONLINE",
    "type": "Central Transit Hub",
    "streamUrl": "https://images.unsplash.com/photo-1517649763962-0c623266ddc0?auto=format&fit=crop&w=800&q=80",
    "description": "Jawaharlal Nehru Road arterial and Maidan green buffer."
  },
  {
    "id": "cctv-ccu-03",
    "city": "Kolkata",
    "name": "Vidyasagar Setu (Second Hooghly Bridge)",
    "lat": 22.5577,
    "lon": 88.3247,
    "elevationM": 48,
    "headingDeg": 110,
    "fovDeg": 80,
    "rangeM": 1200,
    "status": "ONLINE",
    "type": "Cable Stayed River Crossing",
    "streamUrl": "https://images.unsplash.com/photo-1567157577867-05ccb1388e66?auto=format&fit=crop&w=800&q=80",
    "description": "High-capacity tollway crossing between Kolkata and Howrah."
  },
  {
    "id": "cctv-maa-01",
    "city": "Chennai",
    "name": "Marina Beach Coastal Promenade",
    "lat": 13.04,
    "lon": 80.28,
    "elevationM": 32,
    "headingDeg": 30,
    "fovDeg": 74,
    "rangeM": 880,
    "status": "ONLINE",
    "type": "Bay of Bengal Littoral Zone",
    "streamUrl": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    "description": "Kamarajar Salai arterial beachfront corridor and littoral wave zone."
  },
  {
    "id": "cctv-maa-02",
    "city": "Chennai",
    "name": "Kathipara Cloverleaf Flyover",
    "lat": 13.0067,
    "lon": 80.2033,
    "elevationM": 28,
    "headingDeg": 240,
    "fovDeg": 80,
    "rangeM": 850,
    "status": "ONLINE",
    "type": "Multi-Level Cloverleaf",
    "streamUrl": "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80",
    "description": "Largest grade-separated cloverleaf flyover junction in South Asia."
  },
  {
    "id": "cctv-maa-03",
    "city": "Chennai",
    "name": "Chennai Port Container Terminal Harbor",
    "lat": 13.085,
    "lon": 80.3,
    "elevationM": 26,
    "headingDeg": 90,
    "fovDeg": 75,
    "rangeM": 1300,
    "status": "ONLINE",
    "type": "Major Port Waterside",
    "streamUrl": "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80",
    "description": "Coromandel coast shipping entrance and breakwater monitoring."
  },
  {
    "id": "cctv-pnq-01",
    "city": "Pune",
    "name": "Mumbai-Pune Expressway Toll Gate",
    "lat": 18.72,
    "lon": 73.48,
    "elevationM": 35,
    "headingDeg": 120,
    "fovDeg": 75,
    "rangeM": 800,
    "status": "ONLINE",
    "type": "High Speed Intercity Corridor",
    "streamUrl": "https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80",
    "description": "Western Ghats Bhor Ghat section ingress monitoring."
  },
  {
    "id": "cctv-amd-01",
    "city": "Ahmedabad",
    "name": "Sabarmati Riverfront Promenade",
    "lat": 23.03,
    "lon": 72.58,
    "elevationM": 22,
    "headingDeg": 10,
    "fovDeg": 78,
    "rangeM": 750,
    "status": "ONLINE",
    "type": "Riverfront Civic Infrastructure",
    "streamUrl": "https://images.unsplash.com/photo-1582510003544-4d00b7f74220?auto=format&fit=crop&w=800&q=80",
    "description": "Dual-tier concrete river promenade and Ellis Bridge approach."
  },
  {
    "id": "cctv-goa-01",
    "city": "Goa",
    "name": "Mormugao Port Harbor Channel",
    "lat": 15.41,
    "lon": 73.8,
    "elevationM": 28,
    "headingDeg": 280,
    "fovDeg": 80,
    "rangeM": 1400,
    "status": "ONLINE",
    "type": "Naval & Commercial Anchorage",
    "streamUrl": "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80",
    "description": "Zuari river estuary and INS Hansa naval aviation coastal approaches."
  },
  {
    "id": "cctv-cok-01",
    "city": "Kochi",
    "name": "Vallarpadam International Container Terminal",
    "lat": 9.98,
    "lon": 76.24,
    "elevationM": 26,
    "headingDeg": 230,
    "fovDeg": 76,
    "rangeM": 1100,
    "status": "ONLINE",
    "type": "Deepwater Transshipment",
    "streamUrl": "https://images.unsplash.com/photo-1559136555-9303baea8ebd?auto=format&fit=crop&w=800&q=80",
    "description": "Kochi backwaters channel and Southern Naval Command littoral fairway."
  },
  {
    "id": "cctv-jai-01",
    "city": "Jaipur",
    "name": "Hawa Mahal & Badi Chaupar Junction",
    "lat": 26.9239,
    "lon": 75.8267,
    "elevationM": 20,
    "headingDeg": 95,
    "fovDeg": 68,
    "rangeM": 500,
    "status": "ONLINE",
    "type": "Heritage Urban Grid",
    "streamUrl": "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80",
    "description": "Walled Pink City heritage market corridor and vehicular transit."
  },
  {
    "id": "cctv-vns-01",
    "city": "Varanasi",
    "name": "Dashashwamedh Ghat Ganga Riverbank",
    "lat": 25.308,
    "lon": 83.01,
    "elevationM": 25,
    "headingDeg": 80,
    "fovDeg": 82,
    "rangeM": 850,
    "status": "ONLINE",
    "type": "Sacred Waterway & Congregation",
    "streamUrl": "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80",
    "description": "Ganges river main ghat surveillance and pedestrian landing."
  },
  {
    "id": "cctv-sml-01",
    "city": "Shimla",
    "name": "The Ridge & Mall Road Civic Plaza",
    "lat": 31.1048,
    "lon": 77.1734,
    "elevationM": 2200,
    "headingDeg": 40,
    "fovDeg": 70,
    "rangeM": 600,
    "status": "ONLINE",
    "type": "Himalayan Ridge Surveillance",
    "streamUrl": "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80",
    "description": "Pedestrian concourse overlooking the Himalayan Pir Panjal range."
  },
  {
    "id": "cctv-leh-01",
    "city": "Leh Ladakh",
    "name": "Leh Main Bazaar & Shanti Stupa Axis",
    "lat": 34.1642,
    "lon": 77.5848,
    "elevationM": 3500,
    "headingDeg": 210,
    "fovDeg": 75,
    "rangeM": 900,
    "status": "ONLINE",
    "type": "High Altitude Strategic Hub",
    "streamUrl": "https://images.unsplash.com/photo-1506521781263-d8422e82f27a?auto=format&fit=crop&w=800&q=80",
    "description": "Indus Valley defense transit and civilian high-altitude hub."
  }
];
